import { StyleSheet } from "react-native";
import { scale } from "react-native-size-matters";
import { Theme } from "../../libs";

export const Styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    imgbg: {
        flex: 1,
        paddingTop: scale(100),
        paddingHorizontal: scale(16),
    },
    content: {
        alignItems: "center",
        marginTop: scale(8),
    },
    done: {
        width: scale(150),
        height: scale(100),
    },
    descText: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(11.5),
        maxWidth: "100%",
        lineHeight: scale(16),
        color: Theme.colors.brown,
        textAlign: "center",
        marginBottom: scale(12),
    },
    descText1: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(11.5),
        maxWidth: "76%",
        lineHeight: scale(16),
        color: Theme.colors.brown,
        textAlign: "center",
        marginBottom: scale(24),
    },
    petImage: {
        width: scale(90),
        height: scale(90),
        marginBottom: scale(8),
        marginTop: scale(8),
    },
    petName: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(12),
        color: Theme.colors.brown,
        textAlign: "center",
        marginBottom: scale(16),
    },
    stepRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: scale(32),
    },
    stepButton: {
        width: scale(40),
        height: scale(40),
        borderRadius: scale(20),
        borderWidth: 2,
        borderColor: Theme.colors.brown,
        alignItems: "center",
        justifyContent: "center",
        marginHorizontal: scale(12),
        shadowColor: Theme.colors.black,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    stepButtonText: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(18),
        color: Theme.colors.brown,
    },
    stepValueBox: {
        alignItems: "center",
        justifyContent: "center",
        width: scale(120),
        height: scale(42),
        backgroundColor: Theme.colors.white,
        borderRadius: scale(8),
        borderWidth: 2,
        borderColor: Theme.colors.brown,
        flexDirection: "row",
        marginHorizontal: scale(8),
        paddingHorizontal: scale(8),
    },
    stepValue: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(18),
        color: Theme.colors.brown,
        marginRight: scale(6),
    },
    stepsLabel: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(12),
        color: Theme.colors.brown,
    },
    doneButton: {
        width: scale(150),
        height: scale(100),
        justifyContent: "center",
        alignItems: "center",
    },
    doneButtonText: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(18),
        color: Theme.colors.white,
        letterSpacing: 2,
        textAlign: "center",
    },
    doneButtonImage: {
        width: scale(150),
        height: scale(100),
        // borderRadius: scale(12),
    },
    sliderRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width: "85%",
        gap: scale(12),
    },
    sliderWrap: {
        width: scale(180),
        height: scale(44),
    },
    sliderCanvas: {
        width: scale(180),
        height: scale(44),
    },
    stepBtn: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(8),
        borderWidth: 2,
        borderColor: Theme.colors.brown,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: Theme.colors.white,
    },
    stepBtnImg: {
        width: scale(30),
        height: scale(30),
    },
    retroDoneWrap: {
        marginTop: scale(16),
        width: scale(150),
        height: scale(100),
        alignItems: "center",
        justifyContent: "center",
    },
    retroDoneCanvas: {
        ...StyleSheet.absoluteFillObject,
        width: scale(150),
        height: scale(48),
    },
    retroDoneText: {
        fontFamily: Theme.typography.Retro.fontFamily,
        fontSize: scale(16),
        color: Theme.colors.white,
    },
});